# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/nachiket/ece327-s22/labs/jlmrocze-lab4/overlay/tutorial/tutorial.srcs/sources_1/bd/tutorial/ip/tutorial_xbar_1/tutorial_xbar_1.xci
# IP: The module: 'tutorial_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nachiket/ece327-s22/labs/jlmrocze-lab4/overlay/tutorial/tutorial.srcs/sources_1/bd/tutorial/ip/tutorial_xbar_1/tutorial_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tutorial_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/nachiket/ece327-s22/labs/jlmrocze-lab4/overlay/tutorial/tutorial.srcs/sources_1/bd/tutorial/ip/tutorial_xbar_1/tutorial_xbar_1.xci
# IP: The module: 'tutorial_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nachiket/ece327-s22/labs/jlmrocze-lab4/overlay/tutorial/tutorial.srcs/sources_1/bd/tutorial/ip/tutorial_xbar_1/tutorial_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tutorial_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
