set_property SRC_FILE_INFO {cfile:/home/nachiket/lab4/jlmrocze-lab4/overlay/lab4.xdc rfile:../../../../lab4.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins tutorial_i/rst_processing_system7_0_100M/U0/ACTIVE_LOW_PR_OUT_DFF[0].FDRE_PER_N/C]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins tutorial_i/mm_eval/mm_0/inst/mm_inst/mm2s_inst/done_multiply_fclk_reg/C] -to [get_pins tutorial_i/mm_eval/mm_0/inst/mm_inst/mm2s_inst/done_multiply_reg/D]
