# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/nachiket/ece327-s22/labs/jlmrocze-lab4/overlay/tutorial/tutorial.srcs/sources_1/bd/tutorial/ip/tutorial_axi_dma_0/tutorial_axi_dma_0.xci
# IP: The module: 'tutorial_axi_dma_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nachiket/ece327-s22/labs/jlmrocze-lab4/overlay/tutorial/tutorial.srcs/sources_1/bd/tutorial/ip/tutorial_axi_dma_0/tutorial_axi_dma_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tutorial_axi_dma_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/nachiket/ece327-s22/labs/jlmrocze-lab4/overlay/tutorial/tutorial.srcs/sources_1/bd/tutorial/ip/tutorial_axi_dma_0/tutorial_axi_dma_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'tutorial_axi_dma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/nachiket/ece327-s22/labs/jlmrocze-lab4/overlay/tutorial/tutorial.srcs/sources_1/bd/tutorial/ip/tutorial_axi_dma_0/tutorial_axi_dma_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'tutorial_axi_dma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/nachiket/ece327-s22/labs/jlmrocze-lab4/overlay/tutorial/tutorial.srcs/sources_1/bd/tutorial/ip/tutorial_axi_dma_0/tutorial_axi_dma_0.xci
# IP: The module: 'tutorial_axi_dma_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nachiket/ece327-s22/labs/jlmrocze-lab4/overlay/tutorial/tutorial.srcs/sources_1/bd/tutorial/ip/tutorial_axi_dma_0/tutorial_axi_dma_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tutorial_axi_dma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/nachiket/ece327-s22/labs/jlmrocze-lab4/overlay/tutorial/tutorial.srcs/sources_1/bd/tutorial/ip/tutorial_axi_dma_0/tutorial_axi_dma_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'tutorial_axi_dma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/nachiket/ece327-s22/labs/jlmrocze-lab4/overlay/tutorial/tutorial.srcs/sources_1/bd/tutorial/ip/tutorial_axi_dma_0/tutorial_axi_dma_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'tutorial_axi_dma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
