# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/nachiket/lab4/jlmrocze-lab4/overlay/lab4.xdc

# Block Designs: bd/tutorial/tutorial.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial || ORIG_REF_NAME==tutorial} -quiet] -quiet

# IP: bd/tutorial/ip/tutorial_xbar_0/tutorial_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_xbar_0 || ORIG_REF_NAME==tutorial_xbar_0} -quiet] -quiet

# IP: bd/tutorial/ip/tutorial_auto_us_0/tutorial_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_auto_us_0 || ORIG_REF_NAME==tutorial_auto_us_0} -quiet] -quiet

# IP: bd/tutorial/ip/tutorial_auto_us_1/tutorial_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_auto_us_1 || ORIG_REF_NAME==tutorial_auto_us_1} -quiet] -quiet

# IP: bd/tutorial/ip/tutorial_auto_pc_0/tutorial_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_auto_pc_0 || ORIG_REF_NAME==tutorial_auto_pc_0} -quiet] -quiet

# IP: bd/tutorial/ip/tutorial_s00_mmu_0/tutorial_s00_mmu_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_s00_mmu_0 || ORIG_REF_NAME==tutorial_s00_mmu_0} -quiet] -quiet

# IP: bd/tutorial/ip/tutorial_s01_mmu_0/tutorial_s01_mmu_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_s01_mmu_0 || ORIG_REF_NAME==tutorial_s01_mmu_0} -quiet] -quiet

# IP: bd/tutorial/ip/tutorial_axi_mem_intercon_0/tutorial_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_axi_mem_intercon_0 || ORIG_REF_NAME==tutorial_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/tutorial/ip/tutorial_mm_0_0/tutorial_mm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_mm_0_0 || ORIG_REF_NAME==tutorial_mm_0_0} -quiet] -quiet

# IP: bd/tutorial/ip/tutorial_axi_dma_0/tutorial_axi_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_axi_dma_0 || ORIG_REF_NAME==tutorial_axi_dma_0} -quiet] -quiet

# IP: bd/tutorial/ip/tutorial_processing_system7_0_0/tutorial_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_processing_system7_0_0 || ORIG_REF_NAME==tutorial_processing_system7_0_0} -quiet] -quiet

# IP: bd/tutorial/ip/tutorial_xbar_1/tutorial_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_xbar_1 || ORIG_REF_NAME==tutorial_xbar_1} -quiet] -quiet

# IP: bd/tutorial/ip/tutorial_auto_pc_2/tutorial_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_auto_pc_2 || ORIG_REF_NAME==tutorial_auto_pc_2} -quiet] -quiet

# IP: bd/tutorial/ip/tutorial_auto_pc_1/tutorial_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_auto_pc_1 || ORIG_REF_NAME==tutorial_auto_pc_1} -quiet] -quiet

# IP: bd/tutorial/ip/tutorial_processing_system7_0_axi_periph_0/tutorial_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==tutorial_processing_system7_0_axi_periph_0} -quiet] -quiet

# IP: bd/tutorial/ip/tutorial_rst_processing_system7_0_100M_0/tutorial_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==tutorial_rst_processing_system7_0_100M_0} -quiet] -quiet

# XDC: bd/tutorial/tutorial_ooc.xdc
